#!/bin/sh
chown -R root /etc/VirtualBox/
chgrp vboxadmin /etc/VirtualBox
chmod 775 /etc/VirtualBox/
cd /etc/VirtualBox/
chmod -R 000 *
chgrp vboxadmin VirtualBox.xml
chmod 664 VirtualBox.xml
chgrp -R vboxadmin Machines/ HardDisks/
chmod 775 Machines
find Machines/ -type f -exec chmod 644 {} +
find Machines/ -type d -exec chmod 755 {} +
for i in Machines/*; do
mkdir -p $i/Logs
done
chmod 777 Machines/*/Logs
chmod 775 HardDisks/
chgrp vboxusers HardDisks/*
chmod 666 HardDisks/*
#chmod 666 /dev/storage/*
mkdir /var/run/media
echo "Permisos de virtualbox reparados en $HOSTNAME"
reglas_udev(){
	archivo_reglas="/etc/udev/rules.d/69-vbox-discos-maipussy.rules"
	#archivo_discos="/etc/VirtualBox/discos_vbox"
	echo "#Archivo de reglas creado para mantener sanos los permisos de las maquinas virtuales" > $archivo_reglas
	echo "#Esta cosa se crea automaticamente =)" >> $archivo_reglas
	for disco in $(ls -l /dev/storage | grep -v "root ->" | grep -v "swap ->" | awk '{print $9 $11}')
	do
		nombre=$(echo $disco | sed 's/[../].*$//')
		disco=$(echo $disco | sed 's/^.*[../]//')
		echo "$nombre::$disco agregado a udev"
		echo "" >> $archivo_reglas
		echo "#$nombre" >> $archivo_reglas
		if [ "$nombre" == "windows-snap" ]; then
			echo "KERNEL==\"$disco\",GROUP=\"vboxusers\",MODE=\"0666\"" >> $archivo_reglas
		else 
			if [ "$nombre" == "windowsVTR" ]; then
				echo "KERNEL==\"$disco\",GROUP=\"disk\",MODE=\"0666\"" >> $archivo_reglas
			else
				echo "KERNEL==\"$disco\",GROUP=\"vboxusers\",MODE=\"0660\"" >> $archivo_reglas
			fi
		fi
	done
	echo "Reglas UDev Actualizadas"
}
reglas_udev
service udev restart
